# Generated by Django 4.1.7 on 2023-03-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
