# Generated by Django 4.1.6 on 2023-02-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="id",
            new_name="project_id",
        ),
    ]
