# Generated by Django 4.1.7 on 2023-03-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_review_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
